service: inward-core-api-microservices

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: "*"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "*"

layers:
  dependencies:
    path: shared-dependencies