service: user

plugins:
  - serverless-latest-layer-version

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  getUser:
    handler: handler.getUser
    description: invoke getUser function from User service
    events:
      - http:
          path: users
          method: get
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:836509539324:layer:dependencies:latest

  sendUserInfo:
    handler: handler.sendUserInfo
    description: invoke sendUserInfo function from User service
    events:
      - http:
          path: users/sendUserInfo
          method: get
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:836509539324:layer:dependencies:latest
