service: user

# plugins:
#   - serverless-latest-layer-version

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    description: invoke hello function from User service
    events:
      - http:
          path: users
          method: post
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:836509539324:layer:dependencies:6
